version: '3.8'

services:
  app:
    build:
      context: ./app
      #dockerfile: Dockerfile
    #image: "alzkb_site:${ALZKB_ENV}-${TAG}"
    #tty: true
    #stdin_open: true
    env_file:
      - ./config/.env.common
      - ./config/.env.node
    #environment:
      #- NODE_ENV=${ALZKB_ENV}
      #- PORT=5000
    ports:
      - 5000:5000
