services:
  alzkb:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: "alzkb_site_dev"
    tty: true
    stdin_open: true
    ports:
      - "5000:5000"
  nginx:
    restart: always
    build:
      context: ./nginx
    image: "alzkb_nginx_dev"
    ports:
      - "80:80"
