services:
  alzkb:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: "alzkb_site"
    tty: true
    stdin_open: true
    env_file:
      ./app/config/alzkb.env
  nginx:
    restart: always
    build:
      context: ./nginx
    image: "alzkb_nginx"
    ports:
      - "80:80"
