services:
  alzkb:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: "moorelab/alzkb_site"
    tty: true
    stdin_open: true
    environment:
      - NODE_ENV=${ALZKB_ENV}
      - PORT=5000
    ports:
      - "5000:5000"
  nginx:
    restart: always
    build:
      context: ./nginx
    image: "moorelab/alzkb_nginx"
    ports:
      - "80:80"
    depends_on:
      - alzkb
