version: '3.8'

services:
  alzkb:
    build:
      context: ./app
      dockerfile: Dockerfile
    #image: "moorelab/alzkb_site:${ALZKB_ENV}-${TAG}"
    image: "alzkb_site:${ALZKB_ENV}-${TAG}"
    tty: true
    stdin_open: true
    environment:
      - NODE_ENV=${ALZKB_ENV}
      - PORT=5000
    ports:
      - "5000:5000"
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    #image: "moorelab/alzkb_nginx:${ALZKB_ENV}-${TAG}"
    image: "alzkb_nginx:${ALZKB_ENV}-${TAG}"
    ports:
      - "80:80"
    depends_on:
      - alzkb
  neo4j:
    build:
      context: ./neo4j
      dockerfile: Dockerfile
    image: 'alzkb_neo4j:${ALZKB_ENV}-${TAG}'
    environment:
      - NEO4J_browser_post__connect__cmd=guide intro;play ${ALZKB_URL}/${ALZKB_ABOUT};play ${ALZKB_URL}/${ALZKB_SAMPLES}
      - NEO4J_read__only=true
      - NEO4J_dbms_security_auth__enabled=false
      - NEO4J_dbms_default__listen__address=0.0.0.0
      - NEO4J_dbms_connector_http_enabled=true
      - NEO4J_dbms_connector_https_enabled=false
      - NEO4J_dbms_security_procedures_unrestricted=gds.*,apoc.*
    volumes:
      - '/data/neo4j/data:/var/lib/neo4j/data'
      - '/data/neo4j/logs:/var/lib/neo4j/logs'
      - '/data/neo4j/import:/var/lib/neo4j/import'
      - '/data/neo4j/plugins:/var/lib/neo4j/plugins'
      - '/data/neo4j/dumps:/var/lib/neo4j/dumps'
    ports:
      - 7474:7474
      - 7687:7687
    restart: on-failure
