services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile_production
    image: "alzkb_app"
    tty: true
    stdin_open: true
    ports:
      - "5001:5001"
  nginx:
    restart: always
    build:
      context: ./nginx
    image: "alzkb_nginx"
    ports:
      - "80:80"
