version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
    env_file:
      - ./config/.env.nginx
    restart: always
    ports:
      - 80:80
    command: /bin/bash -c "envsubst < alzkb.template > default.conf && nginx -g 'daemon off;'"
