version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
    env_file:
      - ./config/.env.common
      - ./config/.env.nginx
    restart: always
    ports:
      - 80:80
    #replace ONLY env variables found in the template 
    command: /bin/bash -c "envsubst \"$$(printf '$${%s} ' $$(env | cut -d'=' -f1))\" < alzkb.template > default.conf && nginx -g 'daemon off;'"
